name: Build Mosiak OS images

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install podman binfmt-support qemu-user-static ccache

      - name: Build
        run: build-docker.sh

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: raspi-package
          path: ${{github.workspace}}/deplay/*.img
